return {
	{
		"catppuccin/nvim",
		lazy = false,
		priority = 1000,
		name = "catppuccin",
		opts = {
			flavour = "mocha",
			transparent = "true",
			styles = {
				sidebars = "transparent",
				floats = "transparent",
			},
			integrations = {
				aerial = true,
				alpha = true,
				cmp = true,
				dashboard = true,
				flash = true,
				gitsigns = true,
				headlines = true,
				illuminate = true,
				indent_blankline = { enabled = true },
				leap = true,
				lsp_trouble = true,
				mason = true,
				markdown = true,
				mini = true,
				native_lsp = {
					enabled = true,
					underlines = {
						errors = { "undercurl" },
						hints = { "undercurl" },
						warnings = { "undercurl" },
						information = { "undercurl" },
					},
				},
				navic = { enabled = true, custom_bg = "lualine" },
				neotest = true,
				neotree = true,
				noice = true,
				notify = true,
				semantic_tokens = true,
				telescope = true,
				treesitter = true,
				treesitter_context = true,
				which_key = true,
			},
		},
		config = function()
			-- vim.cmd([[colorscheme NeoSolarized]])
			vim.cmd([[colorscheme catppuccin]])
			-- vim.cmd([[colorscheme github_dark_default]])
		end,
	},
	{
		"matthewtodd/vim-twilight",
		name = "twilight",
	},

	{ "jnurmine/Zenburn", name = "zenburn" },
	{ "vim-scripts/xoria256.vim", name = "xoria" },
	{ "nanotech/jellybeans.vim", name = "jellybeans" },
	{ "morhetz/gruvbox", name = "gruvbox" },
	{ "zeis/vim-kolor", name = "kolor" },
	{ "tomasr/molokai", name = "molokai" },
	{ "altercation/vim-colors-solarized", name = "solarized" },
	{ "ayu-theme/ayu-vim", name = "ayu" },
	{ "fneu/breezy", name = "breezy" },
	{ "dim13/smyck.vim", name = "smyck" },
	{ "joshdick/onedark.vim", name = "onedark" },
	{ "folke/tokyonight.nvim", name = "tokyonight" },
	{ "haishanh/night-owl.vim", name = "night-owl" },
	{ "NLKNguyen/papercolor-theme", name = "papercolor" },
	{ "skbolton/embark", name = "embark" },
	{ "iCyMind/NeoSolarized", name = "NeoSolarized" },
	{ "arcticicestudio/nord-vim", branch = "main", name = "nord" },
	{ "franbach/miramare", name = "miramare" },
	{ "srcery-colors/srcery-vim", name = "srcery" },
	{ "vimoxide/vim-cinnabar", name = "cinnabar" },
	{ "fenetikm/falcon", name = "falcon" },
	{ "sainnhe/forest-night", name = "forest-night" },
	{ "sainnhe/gruvbox-material", name = "gruvbox-material" },
	{ "sainnhe/edge", name = "edge" },
	{ "sainnhe/sonokai", name = "sonokai" },
	{ "aonemd/quietlight.vim", name = "quietlight" },
}
